### ISSUE TITLE
好像不能多轮

### ISSUE THREAD

**Issue by xueyouluo** [tianzhen889/KimiChatToV1#1]
大佬试过多轮对话吗？我试了老是提示chatid不存在

**Comment by tianzhen889** [comment]
你的意思是重新开启一个对话吗？这确实是个问题，因为我之前调试的时候，只考虑了chatgpt，ama问天这类软件的提示词，在这类软件中应该是可以重开会话的，但是其他请求方式可能会出现问题，确实会可能出现不能重开会话的情况。

**Comment by tianzhen889** [comment]
chatid不存在？你是用的什么软件或者怎么请求的，可以详细说下吗

**Comment by xueyouluo** [comment]
不好意思可能没有说清楚。 我是想把kimi接到我自己的服务里面，我试着把您的代码抽出来，我理解主要就是先创建一个chat，获取chat_id，然后再调用对话。我现在是第一次对话是正常的，但是发送第二个query过去https://kimi.moonshot.cn/api/chat/{chat_id}/completion/的时候，kimi这边返回错误说chat_id不存在（我传入的还是刚刚的那个chat_id）

**Comment by tianzhen889** [comment]
你主要抽取了我代码中的哪个函数呢，如果你使用了/v1/chat/completions这个接口，这个接口下面的函数自己就已经创建了一次chatid（根据请求中携带的消息数来创建的），这么做当时主要是为了解决chatgptnextweb这种软件新开会话的问题。chatid不存在的问题我好像也遇到过，可能是chatid已经失效，如果你手动创建了一个chatid，然后第二次请求时在我的函数中无意又创建了一次chatid，那么之前的chatid可能会失效。另外我的代码主要参考了https://github.com/cheungchazz/cow_plugin_kimichat这个项目，你也可以尝试从他那里抽取代码，毕竟更简洁一些。

**Comment by xueyouluo** [comment]
create_new_chat_session 获取一个chatid，然后根据chatid + query调用stream_chat_responses，获取回复后，继续用chatid + 第二个query调用stream_chat_responses。这时候chatid应该没有新建。但是报错是 这个会话不存在

**Comment by xueyouluo** [comment]
> 你主要抽取了我代码中的哪个函数呢，如果你使用了/v1/chat/completions这个接口，这个接口下面的函数自己就已经创建了一次chatid（根据请求中携带的消息数来创建的），这么做当时主要是为了解决chatgptnextweb这种软件新开会话的问题。chatid不存在的问题我好像也遇到过，可能是chatid已经失效，如果你手动创建了一个chatid，然后第二次请求时在我的函数中无意又创建了一次chatid，那么之前的chatid可能会失效。另外我的代码主要参考了[https://github.com/cheungchazz/cow_plugin_kimichat这个项目，你也可以尝试从他那里抽取代码，毕竟更简洁一些。](https://github.com/cheungchazz/cow_plugin_kimichat%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E4%BD%A0%E4%B9%9F%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E4%BB%8E%E4%BB%96%E9%82%A3%E9%87%8C%E6%8A%BD%E5%8F%96%E4%BB%A3%E7%A0%81%EF%BC%8C%E6%AF%95%E7%AB%9F%E6%9B%B4%E7%AE%80%E6%B4%81%E4%B8%80%E4%BA%9B%E3%80%82)

试了这个代码，好像可以。谢谢大佬
